services:
  - type: web
    name: exoplanets-library
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Exoplanets_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Exoplanetsdb  # Здесь вы даете имя САМОЙ БАЗЕ ДАННЫХ в Render
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    autoDeploy: true

databases:
  - name: Exoplanetsdb  # Это имя должно совпадать с тем, что в services.envVars
    databaseName: Exoplanets  # Фактическое имя БД внутри PostgreSQL (опционально)
    user: Natalia_Volkova  # Имя пользователя (опционально)
    plan: free