services:
  - type: web
    name: world-of-exoplanets
    env: python
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn Exoplanets_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: exoplanetslib
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: exoplanetslib
    databaseName: exoplanets
    user: alex
    plan: free
    region: oregon